<a href="https://colab.research.google.com/github/slaimdex/MN_4-10_Fit/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D0%A0%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [1]:
# Код студента
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [4]:
import numpy as np

a = np.array([2, 4, 6, 8, 10], dtype=np.int32)

print(a)

print(type(a))



[ 2  4  6  8 10]
<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [7]:
# Код студента
import numpy as np

zeros = np.zeros((2, 5), dtype=np.float32)
ones = np.ones((2, 4), dtype=np.int64)
full = np.full((2, 3), 7)


print("\nzeros =\n", zeros)
print("\nones =\n", ones)
print("\nfull =\n", full)



zeros =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

ones =
 [[1 1 1 1]
 [1 1 1 1]]

full =
 [[7 7 7]
 [7 7 7]]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [14]:
# Код студента
import numpy as np

a = np.arange(1, 21)
b= np.arange(2, 21, 2)

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [15]:
# Код студента
import numpy as np

b= np.linspace(0, 1 , num=11)

print(b)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [16]:
# Код студента

# Код студента
import numpy as np
a = np.arange(1, 13)
m = a.reshape(3, 4)
print("A =\n", a)
print("M =\n", m)

A =
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
M =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [17]:
# Код студента

# Код студента
import numpy as np

a = np.arange(1, 13)
m = a.reshape((3, 4))

print("M =\n", m)

print("\nВиміри:", m.ndim)
print("\nФорма:", m.shape)
print("\nРозмір:", m.size)
print("\nТип данних:", m.dtype)


M =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Виміри: 2

Форма: (3, 4)

Розмір: 12

Тип данних: int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [18]:

# Код студента
import numpy as np

a = np.array([1.2, 3.5, 5.7, 7.9], dtype=np.float64)
x = a.astype(np.int64)

print(x)

[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [19]:
# Код студента
import numpy as np

a =np.array([10, 20, 30, 40, 50, 60, 70, 80], dtype=np.int16)

print(a[0])

print(a[7])

print(a[2:5])

print(a[1::2])

10
80
[30 40 50]
[20 40 60 80]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [20]:
# Код студента
import numpy as np

a =np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12]
    ], dtype=np.int16)

print("\n",a[1, 2])

print("\n", a[1])

print("\n", a[:, 2] )

print("\n",a[1:3 , 0:2])


 7

 [5 6 7 8]

 [ 3  7 11]

 [[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [21]:
# Код студента
import numpy as np

a = np.arange(1, 16)
view = a[5:10]
view[0:5]= 0
print("a =", a)


a = [ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [22]:
# Код студента
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("\n",(a + b))
print("\n", ( a - b ))
print("\n", (a * b))
print("\n", (a / b) )



 [11 22 33 44 55]

 [ -9 -18 -27 -36 -45]

 [ 10  40  90 160 250]

 [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [23]:
# Код студента
import numpy as np

a = np.array([4, 8, 15, 16, 23, 42])

print("sum:", a.sum())
print("serednie:", a.mean())
print("min:", a.min())
print("max:", a.max())
print("median:", np.median(a))
print("std:", a.std())


sum: 108
serednie: 18.0
min: 4
max: 42
median: 15.5
std: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [24]:
# Код студента
import numpy as np

a = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

print("sum:", a.sum())
print("sum(axis=0):", a.sum(axis=0))
print("sum(axis=1):", a.sum(axis=1))
print("mean(axis=0):", a.mean(axis=0))


sum: 45
sum(axis=0): [12 15 18]
sum(axis=1): [ 6 15 24]
mean(axis=0): [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [25]:
# Код студента
a = np.arange(1, 11)

print("square:", np.square(a))
print("sqrt:", np.sqrt(a))
print("log:", np.log(a))

square: [  1   4   9  16  25  36  49  64  81 100]
sqrt: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
log: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [26]:
# Код студента
import numpy as np

a = np.array([3, 7, 12, 18, 21, 25, 30, 34])

mask = a[a >= 15]
dask = a[a%2==0]
lask = a[(a > 10) & (a < 30)]

print("\n a[mask]:", mask)
print("\n a[mask]:", dask)
print("\n a[mask]:", lask)


 a[mask]: [18 21 25 30 34]

 a[mask]: [12 18 30 34]

 a[mask]: [12 18 21 25]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [27]:
# Код студента
import numpy as np

a = np.array([-5, 3, -2, 8, -1, 10, 0])

view = a[:]
view[a<0] = 0

print(a)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [28]:
# Код студента
rng = np.random.default_rng(seed=42)

integers = rng.integers(0, 100, size=20)

a = integers>50
b= integers<50

print("\nintegers:\n", integers )
print("\nбільше 50 :\n", integers [a] )
print("\nМеньше 50:\n",integers  [b] )



integers:
 [ 8 77 65 43 43 85  8 69 20  9 52 97 73 76 71 78 51 12 83 45]

більше 50 :
 [77 65 85 69 52 97 73 76 71 78 51 83]

Меньше 50:
 [ 8 43 43  8 20  9 12 45]


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [30]:
# Код студента
import numpy as np

a = np.arange(1, 25)
m = a.reshape(4, 6)
n = a.reshape(6, 4)
k = a.reshape(2, 3, 4)

print("\nm:\n", m )
print("\nm shape:", m.shape )
print("\n n:\n", n )
print("\n n shape:", n.shape )
print("\nk:\n", k )
print("\nk shape:", k.shape )


m:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

m shape: (4, 6)

 n:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

 n shape: (6, 4)

k:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

k shape: (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [31]:
# Код студента
import numpy as np

a = np.array([[1, 2],
     [3, 4]])
b= np.array([[5, 6],
     [7, 8]])

print("concatenate axis=0:\n", np.concatenate([a, b], axis=0))
print("\nconcatenate axis=1:\n", np.concatenate([a, b], axis=1))


concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [32]:
# Код студента
import numpy as np

a = np.arange(1, 13)
m = a.reshape(3, 4)

print("\nravel:", m.ravel())
print("flatten:", m.flatten())


ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [33]:
# Код студента
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("a + b =", a + b)
print("a / b =", a / b)
print("a * 3 =", a * 3)
print("b * 3 =", b * 3)

a + b = [ 3  7 11]
a / b = [2.         1.33333333 1.2       ]
a * 3 = [ 6 12 18]
b * 3 = [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [34]:
# Код студента
import numpy as np

a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
result = np.dot(a, b)

print("a @ b =", a @ b)
print("\n", result)

a @ b = 44

 44


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [35]:
# Код студента
import numpy as np

v = np.array([3, 4])

norm = np.linalg.norm(v)

v_unit = v / norm

print("Еквілідова норма:", norm)
print("Нормалізований вектор:", v_unit)

Еквілідова норма: 5.0
Нормалізований вектор: [0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [36]:
# Код студента
import numpy as np

a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

result = np.cross(a, b)

print("\n", result)


 [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [37]:
# Код студента
import numpy as np

a = np.array([1, 2])
b = np.array([2, 1])

dot = np.dot(a, b)
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)

cos = dot / (norm_a * norm_b)

angle = np.degrees(np.arccos(cos))

print("Кут у градусах:", angle)
print("Косинус кута:", cos)

Кут у градусах: 36.86989764584404
Косинус кута: 0.7999999999999998


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [38]:
# Код студента
import numpy as np

a = np.array([[1, 2, 3],
     [4, 5, 6]])

m=np.transpose(a)
print("\nA.T =\n", a.T)
print("\nтранспортована матриця =\n", m)


A.T =
 [[1 4]
 [2 5]
 [3 6]]

транспортована матриця =
 [[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [39]:
# Код студента
import numpy as np

import numpy as np

a = np.array([[1, 2],
     [3, 4]])
b= np.array([[2, 0],
     [1, 2]])

c = a @ b
g = a * b
print(c)
print(g) #  в випадку С ми перемножуємо самі матриці, а в G тільки їх елементи один на одного

[[ 4  4]
 [10  8]]
[[2 0]
 [3 8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [ ]:
# Код студента
import numpy as np

import numpy as np

a = np.array([[4, 7],
     [2, 6]])

det = np.linalg.det(a)
b = np.linalg.inv(a)
c = a @ b

print("\ndet(A) =", det)
print(c)

### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [40]:
# Код студента
import numpy as np

x = np.array([[2, 1], [1, 3]])
y= np.array([5, 6])
a=np.linalg.solve(x, y)
print (a)


[1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [41]:
# Код студента
import numpy as np

ones = np.ones((4, 4), dtype=np.int64)
a = np.arange(1,17)
k= a.reshape(4, 4)

print(ones @ k)

[[28 32 36 40]
 [28 32 36 40]
 [28 32 36 40]
 [28 32 36 40]]


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [42]:
# Код студента
import numpy as np

a = np.array([[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])

bias = np.array([10])
print("\nX + bias =\n", a + bias)


X + bias =
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [43]:
# Код студента
import numpy as np

a = np.array( [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])

v = np.array([10, 20, 30])
print("\nX + bias =\n", a + v)


X + bias =
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [44]:
# Код студента
import numpy as np

a = np.array( [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]])

mu = a.mean(axis=1)
sigma = a.std(axis=1)
a_std = (a - mu) / sigma

print("Середні після стандартизації:")
print(a_std.mean(axis=1))

print("\nСтандартні відхилення:")
print(a_std.std(axis=1))

Середні після стандартизації:
[-1.22474487  0.          1.22474487]

Стандартні відхилення:
[0. 0. 0.]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [45]:
# Код студента
import numpy as np

rng = np.random.default_rng(seed=42)

integers = rng.integers(1, 100, size=10)

uniform = rng.random(9)

k= uniform.reshape(3,3)

normal = rng.normal(loc=10.0, scale=5.0, size=1000)

mu = np.mean(normal)
sigma = np.std(normal)

print("\n integers:", integers)
print("\n k:", k)
print("\n середнє:", sigma)  # 0.0
print("\n std:", mu)


 integers: [ 9 77 65 44 43 86  9 70 20 10]

 k: [[0.97562235 0.7611397  0.78606431]
 [0.12811363 0.45038594 0.37079802]
 [0.92676499 0.64386512 0.82276161]]

 середнє: 4.937258143882101

 std: 9.854348757172913


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [46]:
# Код студента
import numpy as np

rng = np.random.default_rng(seed=42)


normal = rng.normal(loc=50.0, scale=49.9, size=30)

k=normal>=60
d= normal>= 90

print("\n mean:", np.round(np.mean(normal)))
print("\n median:", np.round(np.median(normal)))
print("\n min and max:", np.round(np.min(normal)), np.round(np.max(normal)))
print("\n >=60 :", np.round(normal[k]),"всього:", np.sum(k))
print("\n >=90:", np.round(normal[d]), "всього:", np.sum(d) )



 mean: 51.0

 median: 55.0

 min and max: -47.0 111.0

 >=60 : [ 65.  87.  97.  94.  89. 106.  73.  68.  94. 111.  77.  68.  71.  71.] всього: 14

 >=90: [ 97.  94. 106.  94. 111.] всього: 5


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [47]:
# Код студента
import numpy as np


sales = np.array([
    [120, 150, 170, 160],
    [80,  90,  100, 110],
    [200, 180, 210, 230]
])

items = ['Товар 1', 'Товар 2', 'Товар 3']
times = ['Місяць 1', 'Місяць 2', 'Місяць 3','Місяць 4' ]

tovar1=sales[0].sum()
tovar2=sales[1].sum()
tovar3=sales[2].sum()

Mounth1=sales[:, 0].sum()
Mounth2=sales[:, 1].sum()
Mounth3=sales[:, 2].sum()
Mounth4=sales[:, 3].sum()


values = [tovar1, tovar2, tovar3]

mounth = [Mounth1,Mounth2,Mounth3,Mounth4]

best_index=np.argmax(values)
best_mounth=np.argmax(mounth)


print("\n","Сума товару 1:", tovar1)
print("Сума товару 2:", tovar2)
print("Сума товару 3:", tovar3)

print("\n","Сума продажів першого місяця:", sales[:, 0].sum())
print("Сума продажів другого місяця:", sales[:, 1].sum())
print("Сума продажів третього місяця:", sales[:, 2].sum())
print("Сума продажів четвертого місяця:", sales[:, 3].sum())


print("\n",f"Найкраще продається {items[best_index]} із сумою {sales[best_index].sum()}")
print(f"Найкраще продається {times[best_mounth]} із сумою {sales[:, [best_mounth]].sum()}")

print("\n","Середня сума продажу товару1:",sales[0].mean())
print("Середня сума продажу товару2:",sales[1].mean())
print("Середня сума продажу товару3:",sales[2].mean())



 Сума товару 1: 600
Сума товару 2: 380
Сума товару 3: 820

 Сума продажів першого місяця: 400
Сума продажів другого місяця: 420
Сума продажів третього місяця: 480
Сума продажів четвертого місяця: 500

 Найкраще продається Товар 3 із сумою 820
Найкраще продається Місяць 4 із сумою 500

 Середня сума продажу товару1: 150.0
Середня сума продажу товару2: 95.0
Середня сума продажу товару3: 205.0


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [52]:
# Код студента
rng = np.random.default_rng(seed=42)

integers = rng.integers(1, 20, size=25)

m =  integers.reshape(5, 5)


print("\n",m)
print("\n","Сума діагоналі:", np.diag(m).sum())

flip_m = np.fliplr(m)

print("\n","Побічна діагональ:", np.diag(flip_m).sum())

print("\n","найбільший аргумент першого рядка:", m[0].max())
print("найбільший аргумент другого рядка:", m[1].max())
print("найбільший аргумент третього рядка:", m[2].max())
print("найбільший аргумент четвертого рядка:", m[3].max())
print("найбільший аргумент п'ятого рядка:", m[4].max())

print("\n","найменьший аргумент першого стовбця:", m[:, 0].min())
print("найменьший аргумент другого стовбця:", m[:, 1].min())
print("найменьший аргумент третього стовбця:", m[:, 2].min())
print("найменьший аргумент четвертого стовбця:", m[:, 3].min())
print("найменьший аргумент п'ятого стовбця:", m[:, 4].min())

a = np.mean(m)
view = m[:]
view[m<a] = 0
print("\n", m)


 [[ 2 15 13  9  9]
 [17  2 14  4  2]
 [11 19 14 15 14]
 [15 10  3 16  9]
 [10  8  4 18 15]]

 Сума діагоналі: 49

 Побічна діагональ: 47

 найбільший аргумент першого рядка: 15
найбільший аргумент другого рядка: 17
найбільший аргумент третього рядка: 19
найбільший аргумент четвертого рядка: 16
найбільший аргумент п'ятого рядка: 18

 найменьший аргумент першого стовбця: 2
найменьший аргумент другого стовбця: 2
найменьший аргумент третього стовбця: 3
найменьший аргумент четвертого стовбця: 4
найменьший аргумент п'ятого стовбця: 2

 [[ 0 15 13  0  0]
 [17  0 14  0  0]
 [11 19 14 15 14]
 [15  0  0 16  0]
 [ 0  0  0 18 15]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [53]:
# Код студента
import numpy as np

x = np.array([[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]])

distances = np.linalg.norm(x[0] - x[1])
distances2 = np.linalg.norm(x[0] - x[2])
distances3 = np.linalg.norm(x[1] - x[2])
print("\n","евклідова відстань між першим та другим рядком:", distances)
print("евклідова відстань між першим та третім рядком:", distances2)
print("евклідова відстань між другим та третім рядком:", distances3)


 евклідова відстань між першим та другим рядком: 1.7320508075688772
евклідова відстань між першим та третім рядком: 5.196152422706632
евклідова відстань між другим та третім рядком: 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [54]:
# Код студента
import numpy as np

rng = np.random.default_rng(seed=42)

integers = rng.integers(1, 10, size=16)

m =  integers.reshape(4, 4)

norms = np.linalg.norm(m, axis=1)

norms_shape = norms.reshape(-1, 1)

normalized_matrix = m / norms_shape

print("Початкова матриця:")
print(m)

print("\nНормалізована матриця:")
print(normalized_matrix)

print(np.linalg.norm(normalized_matrix, axis=1))

Початкова матриця:
[[1 7 6 4]
 [4 8 1 7]
 [2 1 5 9]
 [7 7 7 8]]

Нормалізована матриця:
[[0.09901475 0.69310328 0.59408853 0.39605902]
 [0.35082321 0.70164642 0.0877058  0.61394061]
 [0.1898316  0.0949158  0.474579   0.8542422 ]
 [0.48189987 0.48189987 0.48189987 0.55074271]]
[1. 1. 1. 1.]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [55]:
# Код студента
import numpy as np

x = np.array([[1, 2, 1], [2, 1, -1], [3,-1,2]])
y= np.array([9,8,3])
a=np.linalg.solve(x, y)
print ("\nЗнайдений розв'язок:", a)

check_result = x @ a
print("\nРезультат множення A @ x:", check_result)
print("Початковий вектор y:     ", y)



Знайдений розв'язок: [ 2.22222222  3.44444444 -0.11111111]

Результат множення A @ x: [9. 8. 3.]
Початковий вектор y:      [9 8 3]


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
