<a href="https://colab.research.google.com/github/slaimdex/MN_4-10_Fit/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_1_3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [ ]:
# Код студента


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [ ]:
# Код студента


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [ ]:
# Код студента


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [ ]:
# Код студента


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [ ]:
# Код студента


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [ ]:
# Код студента


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [ ]:
# Код студента


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [ ]:
# Код студента


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [ ]:
# Код студента


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [ ]:
# Код студента


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [1]:
# Код студента
import numpy as np

a = np.arange(1, 16)
view = a[5:10]
view[0:5]= 0
print("a =", a)


a = [ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [2]:
# Код студента
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("\n",(a + b))
print("\n", ( a - b ))
print("\n", (a * b))
print("\n", (a / b) )


 [11 22 33 44 55]

 [ -9 -18 -27 -36 -45]

 [ 10  40  90 160 250]

 [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [ ]:
# Код студента
import numpy as np

a = np.array([4, 8, 15, 16, 23, 42])

print("sum:", a.sum())
print("serednie:", a.mean())
print("min:", a.min())
print("max:", a.max())
print("median:", np.median(a))
print("std:", a.std())


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [ ]:
# Код студента
import numpy as np

a = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

print("sum:", a.sum())
print("sum(axis=0):", a.sum(axis=0))
print("sum(axis=1):", a.sum(axis=1))
print("mean(axis=0):", a.mean(axis=0))


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [ ]:
# Код студента
a = np.arange(1, 11)

print("square:", np.square(a))
print("sqrt:", np.sqrt(a))
print("log:", np.log(a))



## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [1]:
# Код студента
import numpy as np

a = np.array([3, 7, 12, 18, 21, 25, 30, 34])

mask = a[a >= 15]
dask = a[a%2==0]
lask = a[(a > 10) & (a < 30)]

print("\n a[mask]:", mask)
print("\n a[mask]:", dask)
print("\n a[mask]:", lask)


 a[mask]: [18 21 25 30 34]

 a[mask]: [12 18 30 34]

 a[mask]: [12 18 21 25]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [2]:
# Код студента
import numpy as np

a = np.array([-5, 3, -2, 8, -1, 10, 0])

view = a[:]
view[a<0] = 0

print(a)


[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [ ]:
# Код студента
rng = np.random.default_rng(seed=42)

integers = rng.integers(0, 100, size=20)

a = integers>50
b= integers<50

print("\nintegers:\n", integers )
print("\nбільше 50 :\n", integers [a] )
print("\nМеньше 50:\n",integers  [b] )

## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [ ]:
# Код студента
import numpy as np

a = np.arange(1, 25)
m = a.reshape(4, 6)
n = a.reshape(6, 4)
k = a.reshape(2, 3, 4)

print("\nm:\n", m )
print("\nm shape:", m.shape )
print("\n n:\n", n )
print("\n n shape:", n.shape )
print("\nk:\n", k )
print("\nk shape:", k.shape )

### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [ ]:
# Код студента
import numpy as np

a = np.array([[1, 2],
     [3, 4]])
b= np.array([[5, 6],
     [7, 8]])

print("concatenate axis=0:\n", np.concatenate([a, b], axis=0))
print("\nconcatenate axis=1:\n", np.concatenate([a, b], axis=1))

### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [ ]:
# Код студента
import numpy as np

a = np.arange(1, 13)
m = a.reshape(3, 4)

print("\nravel:", m.ravel())
print("flatten:", m.flatten())

## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [ ]:
# Код студента
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("a + b =", a + b)
print("a / b =", a / b)
print("a * 3 =", a * 3)
print("b * 3 =", b * 3)

### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [ ]:
# Код студента
import numpy as np

a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
result = np.dot(a, b)

print("a @ b =", a @ b)
print("\n", result)

### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [ ]:
# Код студента
import numpy as np

v = np.array([3, 4])

norm = np.linalg.norm(v)

v_unit = v / norm

print("Еквілідова норма:", norm)
print("Нормалізований вектор:", v_unit)

### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [3]:
# Код студента
import numpy as np

a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

result = np.cross(a, b)

print("\n", result)


 [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [ ]:
# Код студента
import numpy as np

a = np.array([1, 2])
b = np.array([2, 1])

dot = np.dot(a, b)
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)

cos = dot / (norm_a * norm_b)

angle = np.degrees(np.arccos(cos))

print("Кут у градусах:", angle)
print("Косинус кута:", cos)

## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [ ]:
# Код студента
import numpy as np

a = np.array([[1, 2, 3],
     [4, 5, 6]])

m=np.transpose(a)
print("\nA.T =\n", a.T)
print("\nтранспортована матриця =\n", m)

### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [ ]:
# Код студента
import numpy as np

import numpy as np

a = np.array([[1, 2],
     [3, 4]])
b= np.array([[2, 0],
     [1, 2]])

c = a @ b
g = a * b
print(c)
print(g) #  в випадку С ми перемножуємо самі матриці, а в G тільки їх елементи один на одного

### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [ ]:
# Код студента
import numpy as np

import numpy as np

a = np.array([[4, 7],
     [2, 6]])

det = np.linalg.det(a)
b = np.linalg.inv(a)
c = a @ b

print("\ndet(A) =", det)
print(c)

### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [4]:
# Код студента
import numpy as np

x = np.array([[2, 1], [1, 3]])
y= np.array([5, 6])
a=np.linalg.solve(x, y)
print (a)

[1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [ ]:
# Код студента
import numpy as np

ones = np.ones((4, 4), dtype=np.int64)
a = np.arange(1,17)
k= a.reshape(4, 4)

print(ones @ k)

## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [ ]:
# Код студента
import numpy as np

a = np.array([[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])

bias = np.array([10])
print("\nX + bias =\n", a + bias)

### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [ ]:
# Код студента
import numpy as np

a = np.array( [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])

v = np.array([10, 20, 30])
print("\nX + bias =\n", a + v)

### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
import numpy as np

a = np.array( [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]])

mu = a.mean(axis=1)
sigma = a.std(axis=1)
a_std = (a - mu) / sigma

print("Середні після стандартизації:")
print(a_std.mean(axis=1))

print("\nСтандартні відхилення:")
print(a_std.std(axis=1))

## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [ ]:
# Код студента
import numpy as np

rng = np.random.default_rng(seed=42)

integers = rng.integers(1, 100, size=10)

uniform = rng.random(9)

k= uniform.reshape(3,3)

normal = rng.normal(loc=10.0, scale=5.0, size=1000)

mu = np.mean(normal)
sigma = np.std(normal)

print("\n integers:", integers)
print("\n k:", k)
print("\n середнє:", sigma)  # 0.0
print("\n std:", mu)

### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)


normal = rng.normal(loc=50.0, scale=49.9, size=30)

k=normal>=60
d= normal>= 90

print("\n mean:", np.round(np.mean(normal)))
print("\n median:", np.round(np.median(normal)))
print("\n min and max:", np.round(np.min(normal)), np.round(np.max(normal)))
print("\n >=60 :", np.round(normal[k]),"всього:", np.sum(k))
print("\n >=90:", np.round(normal[d]), "всього:", np.sum(d) )


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [ ]:
# Код студента


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [ ]:
# Код студента


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [ ]:
# Код студента


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [ ]:
# Код студента


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [ ]:
# Код студента


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
